source "https://rubygems.org"

ruby "3.2.4"

gem "rails", "~> 7.1.3", ">= 7.1.3.3"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "rack-cors"

gem "redis", ">= 4.0.1"

gem "tzinfo-data", platforms: %i[ windows jruby ]

gem "bootsnap", require: false
gem "devise"
gem "dotenv"
gem "devise-jwt"
gem "kaminari"
gem "active_model_serializers"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
  gem "factory_bot_rails"
  gem "rspec-rails"
  gem "shoulda-matchers"
  gem "faker"
  gem "rubocop-rails"
  gem "rubocop-rspec"
  gem "annotate"
end

group :development do
end

